2020-06-25 12:03:05,122 p=13335 u=root n=ansible | ERROR! the playbook: test_user.yml could not be found
2020-06-25 12:03:27,752 p=13337 u=root n=ansible | [DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad characters in group names by 
default, this will change, but still be user configurable on deprecation. This feature will be removed in version 2.10.
 Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
2020-06-25 12:03:27,752 p=13337 u=root n=ansible | [WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

2020-06-25 12:03:28,499 p=13337 u=root n=ansible | test-host | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Load key \"/home/manve/.ssh\": Is a directory\r\nmanve@116.203.159.162: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).",
    "unreachable": true
}
2020-06-25 12:04:40,581 p=13346 u=root n=ansible | [DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad characters in group names by 
default, this will change, but still be user configurable on deprecation. This feature will be removed in version 2.10.
 Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
2020-06-25 12:04:40,581 p=13346 u=root n=ansible | [WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

2020-06-25 12:04:43,724 p=13346 u=root n=ansible | test-host | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "ping": "pong"
}
2020-06-25 12:06:33,037 p=13376 u=root n=ansible | [DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad characters in group names by 
default, this will change, but still be user configurable on deprecation. This feature will be removed in version 2.10.
 Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
2020-06-25 12:06:33,038 p=13376 u=root n=ansible | [WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

2020-06-25 12:06:55,990 p=13376 u=root n=ansible | lrcloud | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "ping": "pong"
}
2020-06-25 12:07:00,930 p=13395 u=root n=ansible | [DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad characters in group names by 
default, this will change, but still be user configurable on deprecation. This feature will be removed in version 2.10.
 Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
2020-06-25 12:07:00,931 p=13395 u=root n=ansible | [WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

2020-06-25 12:07:03,525 p=13395 u=root n=ansible | lrcloud | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "ping": "pong"
}
2020-06-25 12:07:52,075 p=13412 u=root n=ansible | lrcloud | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "ping": "pong"
}
2020-06-25 12:10:10,235 p=13430 u=root n=ansible | ERROR! Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/etc/ansible/test_play.yml': line 3, column 10, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- hosts: test_host
   become: true
         ^ here

2020-06-25 12:10:42,013 p=13434 u=root n=ansible | ERROR! Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/etc/ansible/test_play.yml': line 3, column 10, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- hosts: test_host
   become: true
         ^ here

2020-06-25 12:15:24,985 p=13438 u=root n=ansible | ERROR! Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/etc/ansible/test_play.yml': line 7, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - name: Update apt-cache
     apt: update_cache=yes
        ^ here

2020-06-25 12:16:03,593 p=13442 u=root n=ansible | PLAY [lrcloud] *********************************************************************************************************
2020-06-25 12:16:03,608 p=13442 u=root n=ansible | TASK [Gathering Facts] *************************************************************************************************
2020-06-25 12:16:06,849 p=13442 u=root n=ansible | fatal: [lrcloud]: FAILED! => {"msg": "Missing sudo password"}
2020-06-25 12:16:06,851 p=13442 u=root n=ansible | PLAY RECAP *************************************************************************************************************
2020-06-25 12:16:06,851 p=13442 u=root n=ansible | lrcloud                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-06-25 12:17:09,911 p=13462 u=root n=ansible | PLAY [lrcloud] *********************************************************************************************************
2020-06-25 12:17:09,925 p=13462 u=root n=ansible | TASK [Gathering Facts] *************************************************************************************************
2020-06-25 12:17:13,119 p=13462 u=root n=ansible | fatal: [lrcloud]: FAILED! => {"msg": "Missing sudo password"}
2020-06-25 12:17:13,121 p=13462 u=root n=ansible | PLAY RECAP *************************************************************************************************************
2020-06-25 12:17:13,121 p=13462 u=root n=ansible | lrcloud                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-06-25 12:20:36,367 p=13485 u=root n=ansible | PLAY [lrcloud] *********************************************************************************************************
2020-06-25 12:20:36,383 p=13485 u=root n=ansible | TASK [Gathering Facts] *************************************************************************************************
2020-06-25 12:20:39,703 p=13485 u=root n=ansible | fatal: [lrcloud]: FAILED! => {"msg": "Missing sudo password"}
2020-06-25 12:20:39,706 p=13485 u=root n=ansible | PLAY RECAP *************************************************************************************************************
2020-06-25 12:20:39,706 p=13485 u=root n=ansible | lrcloud                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-06-25 12:22:56,671 p=13521 u=root n=ansible | PLAY [lrcloud] *********************************************************************************************************
2020-06-25 12:22:56,684 p=13521 u=root n=ansible | TASK [Gathering Facts] *************************************************************************************************
2020-06-25 12:23:00,272 p=13521 u=root n=ansible | ok: [lrcloud]
2020-06-25 12:23:00,277 p=13521 u=root n=ansible | TASK [Update apt-cache] ************************************************************************************************
2020-06-25 12:23:02,255 p=13521 u=root n=ansible | [WARNING]: Updating cache and auto-installing missing dependency: python-apt

2020-06-25 12:23:02,255 p=13521 u=root n=ansible | fatal: [lrcloud]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "[Errno 2] No such file or directory", "rc": 2}
2020-06-25 12:23:02,257 p=13521 u=root n=ansible | PLAY RECAP *************************************************************************************************************
2020-06-25 12:23:02,257 p=13521 u=root n=ansible | lrcloud                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
